apps/order/urls.py
from django.urls import path
from .views import (
    CreateOrderView,
)


app_name = 'order'


urlpatterns = [
    path('add/', CreateOrderView.as_view(), name='add'),
]

apps/payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    path('', views.CartView, name='payment'),
#     path('orderplaced/', views.order_placed, name='order_placed'),
#     path('error/', views.Error.as_view(), name='error'),
]

apps/shop/urls.py
from django.urls import path, include
from .views import (
    ShopView,
    HomeView
)

app_name = "shop"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('<str:shop_slug>/', ShopView.as_view(), name='shop'),
    path('<str:shop_slug>/cart/', include('apps.cart.urls', namespace='cart')),
    path('<str:shop_slug>/payment/', include('apps.payment.urls', namespace='payment')),
    path('<str:shop_slug>/', include('apps.product.urls', namespace="product")),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('apps.order.urls', namespace='order')),
    path('', include('apps.shop.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/payment/models.py
from django.db import models

# Create your models here.

apps/payment/views.py
from django.shortcuts import render, get_object_or_404
from decimal import Decimal
from ..cart.cart import Cart
from ..shop.models import Shop


def CartView(request, shop_slug=None):
    cart = Cart(request)
    shop = get_object_or_404(Shop, active=True, slug=shop_slug)
    cart_total = cart.get_subtotal_of_product() + Decimal(shop.shipping_fee)
    context = {
        'shop': shop, 
        'cart_total': cart_total
    }
    return render(request, 'payment/payment.html', context)

templates/payment/payment.html
{% extends "base.html" %}
{% load static %}
{% block title %}Shipping Information{% endblock %}
{% block content %}


{% include '_navBar.html' %}




<div id="breadcrumb" class="container-fluid mt-5">
  <div class="row">
      <div class="col p-3">
          <nav aria-label="breadcrumb">
              <ol class="breadcrumb mt-5">
                <li class="breadcrumb-item"><a class="fw-light" href="{% url 'shop:shop' shop_slug=shop.slug %}">{{ shop | upper }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">SHIPPING INFORMATION</li>
              </ol>
            </nav>
      </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col mb-5">
      <a style="color: #fff;" class="w-100 btn btn-md btn-outline-primary" href="{% url 'shop:shop' shop_slug=shop.slug %}">Continue Shopping</a>
    </div>
  </div>
</div>

<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-lg-12">
      <form id="payment-form" method="POST" validate>
        {% csrf_token %}
        <div class="row gy-3">
          <div class="col-md-6">
            <label for="first_name" class="form-label">First Name:</label>
            <input type="text" class="form-control" id="first_name" required>
            <div class="valid-feedback">
              Looks good!
            </div>
          </div>
          <div class="col-md-6">
            <label for="last_name" class="form-label">Last Name:</label>
            <input type="text" class="form-control" id="last_name" required>
            <div class="valid-feedback">
              Looks good!
            </div>
          </div>
          <div class="col-md-6">
            <label for="email" class="form-label">Email:</label>
            <input type="email" class="form-control" id="email" required>
            <div class="valid-feedback">
              Looks good!
            </div>
            
          </div>
          <div class="col-md-6">
            <label for="phone" class="form-label">Phone:</label>
            <input type="tel" class="form-control" id="phone" required>
            <div class="valid-feedback">
              Looks good!
            </div>
            
          </div>
          <div class="col-md-12">
            <label for="address1" class="form-label">Address Line 1:</label>
            <input type="text" class="form-control" id="address1" required>
            <div class="valid-feedback">
              Looks good!
            </div>
            
          </div>
          <div class="col-md-6">
            <label for="address2" class="form-label">Address Line 2:</label>
            <input type="text" class="form-control" id="address2">
            <div class="valid-feedback">
              Looks good!
            </div>
            
          </div>
          <div class="col-md-6">
            <label for="city" class="form-label">City:</label>
            <input type="text" class="form-control" id="city" required>
            <div class="invalid-feedback">
              Please provide a valid city.
            </div>
          </div>
          <div class="col-md-3">
            <label for="province" class="form-label">Province:</label>
            <select class="form-select" id="province" required>
              <option selected disabled value="">Choose...</option>
              <option>Gauteng</option>
              <option>Limpopo</option>
              <option>Mpumalanga</option>
              <option>Kwa-Zulu Natal</option>
              <option>Eastern Cape</option>
              <option>Free State</option>
              <option>North West</option>
              <option>Northern Cape</option>
              <option>Western Cape</option>
            </select>
            <div class="invalid-feedback">
              Please select a valid province.
            </div>
          </div>
          <div class="col-md-3">
            <label for="zip_code" class="form-label">Zip Code:</label>
            <input type="text" class="form-control" id="zip_code" required>
            <div class="invalid-feedback">
              Please provide a valid zip.
            </div>
          </div>
        </div>

        <button type="submit" id="order-button" class="btn btn-md btn-outline-primary mt-5">
          Place Order R{{ cart_total }}
        </button>
        
      </form>
    </div>
    <div class="col-lg-12" id="orderConfirmation">

    </div>
  </div>
</div>


<div id="eft-alert" class="container">
  <div class="row">
    <div class="col-lg-12">
      <p class="">We only offer Electronic Fund Transfer <strong>(EFT)</strong> as payment method at the moment, <br><br>Thank you.</p>
    </div>
  </div>
</div>


{% include 'footer.html' %}


<style>
  .btn-outline-primary {
    border-color: #011126 !important;
    color: #011126 !important;
  }

  .btn-outline-primary:hover {
    background-color: #D9AE79 !important;
    border-color: #D9AE79 !important;
    color: #fff !important;
  }
</style>

<script>
    // {% comment %} Make csrf token availble in JS files {% endcomment %}
    var CSRF_TOKEN = '{{ csrf_token }}';
    var cartTotal = '{{ cart.get_total_price}}';
    var cartTotal = cartTotal.toString();
    var cartTotal = cartTotal.replace('.', '');
    var cartTotal = parseInt(cartTotal)
    var shop = '{{shop}}'
    var order_url = "{% url 'order:add' %}";
</script>

<script src="{% static 'payment.js' %}" data-rel-js></script>

{% endblock %}